# Generated by Django 5.1.2 on 2024-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma_serie',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='turma_serie',
            name='turma',
        ),
        migrations.AddField(
            model_name='jogo',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turma',
            name='serie',
            field=models.CharField(default='9º ', max_length=100, verbose_name='serie'),
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
        migrations.DeleteModel(
            name='Turma_Serie',
        ),
    ]
