# Generated by Django 5.1.2 on 2024-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='alternativa1',
            field=models.CharField(max_length=100, null=True, verbose_name='alternativa1'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa2',
            field=models.CharField(max_length=100, null=True, verbose_name='alternativa2'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa3',
            field=models.CharField(max_length=100, null=True, verbose_name='alternativa3'),
        ),
        migrations.AddField(
            model_name='questao',
            name='resposta',
            field=models.CharField(max_length=100, null=True, verbose_name='resposta'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='descricao'),
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
    ]
