# Generated by Django 5.1.2 on 2024-10-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_questao_alternativa1_questao_alternativa2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=255, null=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='senha',
            field=models.CharField(max_length=64, null=True, verbose_name='senha'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa1',
            field=models.CharField(max_length=100, verbose_name='alternativa1'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa2',
            field=models.CharField(max_length=100, verbose_name='alternativa2'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa3',
            field=models.CharField(max_length=100, verbose_name='alternativa3'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta',
            field=models.CharField(max_length=100, verbose_name='resposta'),
        ),
        migrations.CreateModel(
            name='Turma_Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
        ),
    ]
