# Generated by Django 5.1.2 on 2024-12-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_aluno_progresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='professor@email.com', max_length=254, unique=True, verbose_name='email'),
        ),
    ]
