# Generated by Django 5.1.2 on 2024-12-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_professor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='professor@email.com', max_length=254, unique=True, verbose_name='email'),
        ),
    ]
